# SPDX-FileCopyrightText: Copyright © 2021 snek.at
# SPDX-License-Identifier: EUPL-1.2
#
# Use of this source code is governed by an EUPL-1.2 license that can be found
# in the LICENSE file at https://snek.at/license

# https://help.github.com/en/articles/workflow-syntax-for-github-actions#name
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # https://help.github.com/en/articles/virtual-environments-for-github-actions#default-environment-variables
      # https://github.com/actions/checkout
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
      - name: Github package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsid
      - name: Install and Build 🔧 
        run: |
          npm install
          npm run deploy
          wget https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/jaen-storage/jaen-data.json
